# Data exploration

### Import dataset obtained from Kaggle containing startup list

In [1]:
import pandas as pd

In [2]:
pd.set_option("display.max_columns", None)
startups = pd.read_csv('../dataset/investments_VC.csv')

In [3]:
startups.sample(5)

,permalink,name,homepage_url,category_list,market,funding_total_usd,status,country_code,state_code,region,city,funding_rounds,founded_at,founded_month,founded_quarter,founded_year,first_funding_at,last_funding_at,seed,venture,equity_crowdfunding,undisclosed,convertible_note,debt_financing,angel,grant,private_equity,post_ipo_equity,post_ipo_debt,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
26470,/organization/mevion-medical-systems-inc,"Mevion Medical Systems, Inc.",http://mevion.com,|Biotechnology|,Biotechnology,"4,45,00,000",operating,USA,MA,Boston,Littleton,2.0,NaN,NaN,NaN,NaN,2009-01-01,2011-03-18,0.0,44500000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
42784,/organization/the-logic-group,The Logic Group,http://www.the-logic-group.com/,|Customer Service|Mobile Payments|Payments|,Mobile Payments,-,acquired,GBR,NaN,Hampshire,NaN,1.0,1986-01-01,1986-01,1986-Q1,1986.0,2011-07-01,2011-07-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14647,/organization/ezcater,ezCater,http://www.ezcater.com,|Restaurants|Startups|Office Space|Hospitality...,Restaurants,"67,90,000",operating,USA,MA,Boston,Boston,3.0,2007-08-01,2007-08,2007-Q3,2007.0,2011-10-05,2014-04-15,630000.0,6160000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24381,/organization/livesafe,LiveSafe,http://www.livesafemobile.com,|Social Media|,Social Media,"69,98,000",operating,USA,VA,"Washington, D.C.",Arlington,3.0,2012-02-01,2012-02,2012-Q1,2012.0,2013-06-03,2014-03-25,0.0,6500000.0,0.0,0.0,0.0,498000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6500000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40261,/organization/spotxchange,SpotXchange,http://www.spotxchange.com,|Advertising|,Advertising,"1,20,00,000",acquired,USA,CO,Denver,Westminster,2.0,2006-11-01,2006-11,2006-Q4,2006.0,2008-01-01,2010-12-15,0.0,12000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
startups.shape

(54294, 39)

### It looks like there are several rows with all NaN and some columns that will not be very useful. In the following lines I will focus on fixing this

In [5]:
startups.isnull().sum()

permalink                4856
name                     4857
homepage_url             8305
category_list            8817
 market                  8824
 funding_total_usd       4856
status                   6170
country_code            10129
state_code              24133
region                  10129
city                    10972
funding_rounds           4856
founded_at              15740
founded_month           15812
founded_quarter         15812
founded_year            15812
first_funding_at         4856
last_funding_at          4856
seed                     4856
venture                  4856
equity_crowdfunding      4856
undisclosed              4856
convertible_note         4856
debt_financing           4856
angel                    4856
grant                    4856
private_equity           4856
post_ipo_equity          4856
post_ipo_debt            4856
secondary_market         4856
product_crowdfunding     4856
round_A                  4856
round_B                  4856
round_C                  4856
round_D                  4856
round_E                  4856
round_F                  4856
round_G                  4856
round_H                  4856
dtype: int64

In [6]:
startups.dropna(axis=0, how='all', inplace=True)

In [7]:
startups.isnull().sum()

permalink                   0
name                        1
homepage_url             3449
category_list            3961
 market                  3968
 funding_total_usd          0
status                   1314
country_code             5273
state_code              19277
region                   5273
city                     6116
funding_rounds              0
founded_at              10884
founded_month           10956
founded_quarter         10956
founded_year            10956
first_funding_at            0
last_funding_at             0
seed                        0
venture                     0
equity_crowdfunding         0
undisclosed                 0
convertible_note            0
debt_financing              0
angel                       0
grant                       0
private_equity              0
post_ipo_equity             0
post_ipo_debt               0
secondary_market            0
product_crowdfunding        0
round_A                     0
round_B                     0
round_C                     0
round_D                     0
round_E                     0
round_F                     0
round_G                     0
round_H                     0
dtype: int64

In [8]:
startups.columns = [col.strip() for col in startups.columns]

In [9]:
startups.shape

(49438, 39)

In [10]:
startups.sample(5)

,permalink,name,homepage_url,category_list,market,funding_total_usd,status,country_code,state_code,region,city,funding_rounds,founded_at,founded_month,founded_quarter,founded_year,first_funding_at,last_funding_at,seed,venture,equity_crowdfunding,undisclosed,convertible_note,debt_financing,angel,grant,private_equity,post_ipo_equity,post_ipo_debt,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
39163,/organization/snapt,Snapt,http://www.snapt.net,|Open Source|Software|,Open Source,-,operating,ZAF,NaN,Johannesburg,Johannesburg,2.0,2011-01-01,2011-01,2011-Q1,2011.0,2011-08-01,2014-09-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27210,/organization/mobvoi,Mobvoi,http://www.mobvoi.com,|Mobile|,Mobile,"1,16,20,000",operating,CHN,NaN,Beijing,Beijing,2.0,2012-01-01,2012-01,2012-Q1,2012.0,2012-01-01,2014-02-24,0.0,11620000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1620000.0,10000000.0,0.0,0.0,0.0,0.0,0.0,0.0
43097,/organization/thinkr,Thinkr,http://thin.kr,|Opinions|Photo Sharing|Mobile|Social Media|,Photo Sharing,"1,50,000",operating,BRA,NaN,Rio de Janeiro,Rio De Janeiro,1.0,2013-01-01,2013-01,2013-Q1,2013.0,2013-04-01,2013-04-01,150000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25269,/organization/makers-alley,Makers Alley,NaN,NaN,NaN,"25,000",operating,NaN,NaN,NaN,NaN,1.0,2011-07-01,2011-07,2011-Q3,2011.0,2012-06-04,2012-06-04,25000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31672,/organization/payworks,payworks,http://www.payworksmobile.com,|Mobile Payments|Payments|Mobile|,Payments,-,operating,DEU,NaN,Munich,Munich,1.0,2012-01-01,2012-01,2012-Q1,2012.0,2013-10-16,2013-10-16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [11]:
startups.columns

Index(['permalink', 'name', 'homepage_url', 'category_list', 'market',
       'funding_total_usd', 'status', 'country_code', 'state_code', 'region',
       'city', 'funding_rounds', 'founded_at', 'founded_month',
       'founded_quarter', 'founded_year', 'first_funding_at',
       'last_funding_at', 'seed', 'venture', 'equity_crowdfunding',
       'undisclosed', 'convertible_note', 'debt_financing', 'angel', 'grant',
       'private_equity', 'post_ipo_equity', 'post_ipo_debt',
       'secondary_market', 'product_crowdfunding', 'round_A', 'round_B',
       'round_C', 'round_D', 'round_E', 'round_F', 'round_G', 'round_H'],
      dtype='object')

In [12]:
startups.drop(['homepage_url','category_list', 'state_code', 'region', 'undisclosed', 'founded_month', 'founded_quarter'], axis=1, inplace=True)

In [13]:
startups.head()

,permalink,name,market,funding_total_usd,status,country_code,city,funding_rounds,founded_at,founded_year,first_funding_at,last_funding_at,seed,venture,equity_crowdfunding,convertible_note,debt_financing,angel,grant,private_equity,post_ipo_equity,post_ipo_debt,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
0,/organization/waywire,#waywire,News,"17,50,000",acquired,USA,New York,1.0,2012-06-01,2012.0,2012-06-30,2012-06-30,1750000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,/organization/tv-communications,&TV Communications,Games,"40,00,000",operating,USA,Los Angeles,2.0,NaN,NaN,2010-06-04,2010-09-23,0.0,4000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,/organization/rock-your-paper,'Rock' Your Paper,Publishing,"40,000",operating,EST,Tallinn,1.0,2012-10-26,2012.0,2012-08-09,2012-08-09,40000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,/organization/in-touch-network,(In)Touch Network,Electronics,"15,00,000",operating,GBR,London,1.0,2011-04-01,2011.0,2011-04-01,2011-04-01,1500000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,/organization/r-ranch-and-mine,-R- Ranch and Mine,Tourism,"60,000",operating,USA,Fort Worth,2.0,2014-01-01,2014.0,2014-08-17,2014-09-26,0.0,0.0,60000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
startups.isnull().sum()

permalink                   0
name                        1
market                   3968
funding_total_usd           0
status                   1314
country_code             5273
city                     6116
funding_rounds              0
founded_at              10884
founded_year            10956
first_funding_at            0
last_funding_at             0
seed                        0
venture                     0
equity_crowdfunding         0
convertible_note            0
debt_financing              0
angel                       0
grant                       0
private_equity              0
post_ipo_equity             0
post_ipo_debt               0
secondary_market            0
product_crowdfunding        0
round_A                     0
round_B                     0
round_C                     0
round_D                     0
round_E                     0
round_F                     0
round_G                     0
round_H                     0
dtype: int64

### I have already cleaned the dataset from rows containing all NaN's, but there are still a few NaN's in several columns. Let's tackle this

In [15]:
startups = startups[pd.notnull(startups['status'])]

In [16]:
startups.status.isnull().sum()

0

In [17]:
startups = startups[pd.notnull(startups['name'])]

### Given that one of the variables I want to look at is the time between founding and first funding round, I'm going to have to delete those in which either is NaN

In [18]:
startups = startups[pd.notnull(startups['founded_at'])]

In [19]:
startups.dropna(axis=0, how="any", inplace=True)

In [20]:
startups.shape

(32765, 32)

In [21]:
startups.status.value_counts()

operating    28315
acquired      2748
closed        1702
Name: status, dtype: int64

In [22]:
startups.city.value_counts()

San Francisco      2219
New York           1951
London             1022
Palo Alto           484
Austin              462
                   ...
Avon-les-roches       1
Puerto Madero         1
Montebelluna          1
North Wales           1
Ledbury               1
Name: city, Length: 3429, dtype: int64

### Later on I will have to group some cities into an "Other" category before training the model

In [23]:
startups.sample(5)

,permalink,name,market,funding_total_usd,status,country_code,city,funding_rounds,founded_at,founded_year,first_funding_at,last_funding_at,seed,venture,equity_crowdfunding,convertible_note,debt_financing,angel,grant,private_equity,post_ipo_equity,post_ipo_debt,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
14610,/organization/eyenalyze,Eyenalyze,Finance,"1,86,000",operating,USA,Conway,1.0,2009-04-01,2009.0,2013-07-23,2013-07-23,0.0,0.0,186000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1405,/organization/affinion-group,Affinion Group,Product Development Services,"15,00,000",operating,USA,Stamford,1.0,2005-01-01,2005.0,2013-11-04,2013-11-04,0.0,1500000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40776,/organization/stormmq,StormMQ,PaaS,"1,49,167",operating,GBR,Skipton,1.0,2010-03-02,2010.0,2010-03-01,2010-03-01,149167.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
376,/organization/71lbs,71lbs,Small and Medium Businesses,"24,50,000",operating,USA,Fort Lauderdale,5.0,2011-03-03,2011.0,2012-03-20,2014-06-08,450000.0,0.0,0.0,0.0,0.0,2000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
42736,/organization/the-highway-girl,The Highway Girl,Curated Web,-,operating,USA,Atlanta,1.0,2005-02-01,2005.0,2008-05-01,2008-05-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### Let's take a look at the data types and check that they are correct

In [24]:
startups.dtypes

permalink                object
name                     object
market                   object
funding_total_usd        object
status                   object
country_code             object
city                     object
funding_rounds          float64
founded_at               object
founded_year            float64
first_funding_at         object
last_funding_at          object
seed                    float64
venture                 float64
equity_crowdfunding     float64
convertible_note        float64
debt_financing          float64
angel                   float64
grant                   float64
private_equity          float64
post_ipo_equity         float64
post_ipo_debt           float64
secondary_market        float64
product_crowdfunding    float64
round_A                 float64
round_B                 float64
round_C                 float64
round_D                 float64
round_E                 float64
round_F                 float64
round_G                 float64
round_H                 float64
dtype: object

### Funding_total_usd needs to be an integer;  Founded_at, first_funding_at, and last_funding_at should be a date, let's change those via functions

In [25]:
def funding_conversor(x):
    if x in ["-", " -   "]:
        return 0
    else:
        split = x.split(",")
        return int(''.join(split))

In [26]:
startups['funding_total_usd'] = startups.funding_total_usd.apply(funding_conversor)

In [27]:
startups['funding_total_usd']

0         1750000
2           40000
3         1500000
4           60000
8               0
           ...
49430    15419877
49432     2686600
49433      320000
49435       97398
49437    45000000
Name: funding_total_usd, Length: 32765, dtype: int64

In [28]:
startups['founded_at']= pd.to_datetime(startups['founded_at'])

In [30]:
startups.loc[startups.first_funding_at.str.contains("20-06-14"), "first_funding_at"]

1492    0020-06-14
Name: first_funding_at, dtype: object

In [31]:
startups.loc[startups.first_funding_at.str.contains("20-06-14"), "first_funding_at"] = "2020-06-14"

In [33]:
startups.loc[startups.first_funding_at.str.contains("19-11-20"), "first_funding_at"]

6661    0019-11-20
Name: first_funding_at, dtype: object

In [34]:
startups.loc[startups.first_funding_at.str.contains("19-11-20"), "first_funding_at"] = "2019-11-20"

In [36]:
startups.loc[startups.first_funding_at.str.contains("201-01-01"), "first_funding_at"]

14524    0201-01-01
Name: first_funding_at, dtype: object

In [40]:
startups = startups[startups["first_funding_at"] != '0201-01-01']

In [43]:
startups.loc[startups.first_funding_at.str.contains("0007-05-13"), "first_funding_at"]

29695    0007-05-13
Name: first_funding_at, dtype: object

In [44]:
startups.loc[startups.first_funding_at.str.contains("0007-05-13"), "first_funding_at"] = '2007-05-13'

In [47]:
startups.loc[startups.first_funding_at.str.contains("0011-11-14"), "first_funding_at"]

37313    0011-11-14
Name: first_funding_at, dtype: object

In [48]:
startups.loc[startups.first_funding_at.str.contains("0011-11-14"), "first_funding_at"] = '2011-11-14'

In [49]:
startups['first_funding_at']= pd.to_datetime(startups['first_funding_at'])

In [50]:
startups['last_funding_at']= pd.to_datetime(startups['last_funding_at'])

In [51]:
startups.shape

(32764, 32)

### I am now going to add a new column that will represent the time difference between the founding date and the date the startup received it's first funding

In [52]:
startups['delta_founded_vs_firstfunding'] = startups.first_funding_at - startups.founded_at

In [53]:
startups.head()

,permalink,name,market,funding_total_usd,status,country_code,city,funding_rounds,founded_at,founded_year,first_funding_at,last_funding_at,seed,venture,equity_crowdfunding,convertible_note,debt_financing,angel,grant,private_equity,post_ipo_equity,post_ipo_debt,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H,delta_founded_vs_firstfunding
0,/organization/waywire,#waywire,News,1750000,acquired,USA,New York,1.0,2012-06-01,2012.0,2012-06-30,2012-06-30,1750000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,29 days
2,/organization/rock-your-paper,'Rock' Your Paper,Publishing,40000,operating,EST,Tallinn,1.0,2012-10-26,2012.0,2012-08-09,2012-08-09,40000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-78 days
3,/organization/in-touch-network,(In)Touch Network,Electronics,1500000,operating,GBR,London,1.0,2011-04-01,2011.0,2011-04-01,2011-04-01,1500000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0 days
4,/organization/r-ranch-and-mine,-R- Ranch and Mine,Tourism,60000,operating,USA,Fort Worth,2.0,2014-01-01,2014.0,2014-08-17,2014-09-26,0.0,0.0,60000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,228 days
8,/organization/004-technologies,004 Technologies,Software,0,operating,USA,Champaign,1.0,2010-01-01,2010.0,2014-07-24,2014-07-24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1665 days

In [54]:
startups.dtypes

permalink                                 object
name                                      object
market                                    object
funding_total_usd                          int64
status                                    object
country_code                              object
city                                      object
funding_rounds                           float64
founded_at                        datetime64[ns]
founded_year                             float64
first_funding_at                  datetime64[ns]
last_funding_at                   datetime64[ns]
seed                                     float64
venture                                  float64
equity_crowdfunding                      float64
convertible_note                         float64
debt_financing                           float64
angel                                    float64
grant                                    float64
private_equity                           float64
post_ipo_equity                          float64
post_ipo_debt                            float64
secondary_market                         float64
product_crowdfunding                     float64
round_A                                  float64
round_B                                  float64
round_C                                  float64
round_D                                  float64
round_E                                  float64
round_F                                  float64
round_G                                  float64
round_H                                  float64
delta_founded_vs_firstfunding    timedelta64[ns]
dtype: object

In [61]:
import numpy as np

In [62]:
def days_to_integer(x):
    return x / np.timedelta64(1, 'D')

In [64]:
startups['delta_founded_vs_firstfunding'] = startups.delta_founded_vs_firstfunding.apply(days_to_integer)

In [65]:
startups.head()

,permalink,name,market,funding_total_usd,status,country_code,city,funding_rounds,founded_at,founded_year,first_funding_at,last_funding_at,seed,venture,equity_crowdfunding,convertible_note,debt_financing,angel,grant,private_equity,post_ipo_equity,post_ipo_debt,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H,delta_founded_vs_firstfunding
0,/organization/waywire,#waywire,News,1750000,acquired,USA,New York,1.0,2012-06-01,2012.0,2012-06-30,2012-06-30,1750000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,29.0
2,/organization/rock-your-paper,'Rock' Your Paper,Publishing,40000,operating,EST,Tallinn,1.0,2012-10-26,2012.0,2012-08-09,2012-08-09,40000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-78.0
3,/organization/in-touch-network,(In)Touch Network,Electronics,1500000,operating,GBR,London,1.0,2011-04-01,2011.0,2011-04-01,2011-04-01,1500000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,/organization/r-ranch-and-mine,-R- Ranch and Mine,Tourism,60000,operating,USA,Fort Worth,2.0,2014-01-01,2014.0,2014-08-17,2014-09-26,0.0,0.0,60000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,228.0
8,/organization/004-technologies,004 Technologies,Software,0,operating,USA,Champaign,1.0,2010-01-01,2010.0,2014-07-24,2014-07-24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1665.0

### For this new column there are some negative values which don't make sense as it's not possible to receive funding wihout existing, hence, I will adjust the dataset for those cases

In [67]:
startups.loc[startups.delta_founded_vs_firstfunding < 0]

,permalink,name,market,funding_total_usd,status,country_code,city,funding_rounds,founded_at,founded_year,first_funding_at,last_funding_at,seed,venture,equity_crowdfunding,convertible_note,debt_financing,angel,grant,private_equity,post_ipo_equity,post_ipo_debt,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H,delta_founded_vs_firstfunding
2,/organization/rock-your-paper,'Rock' Your Paper,Publishing,40000,operating,EST,Tallinn,1.0,2012-10-26,2012.0,2012-08-09,2012-08-09,40000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-78.0
20,/organization/1000memories,1000memories,Curated Web,2535000,acquired,USA,San Francisco,2.0,2010-07-01,2010.0,2010-01-01,2011-02-16,15000.0,2520000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2520000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-181.0
54,/organization/140-proof,140 Proof,Advertising,5500000,operating,USA,San Francisco,2.0,2010-01-11,2010.0,2009-07-01,2011-04-28,0.0,5500000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3000000.0,2500000.0,0.0,0.0,0.0,0.0,0.0,0.0,-194.0
68,/organization/1calendar,1calendar,Education,40000,operating,DNK,Copenhagen,1.0,2009-01-19,2009.0,2008-04-04,2008-04-04,0.0,0.0,0.0,0.0,0.0,40000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-290.0
131,/organization/27-perry,27 Perry,E-Commerce,118000,closed,USA,Boulder,1.0,2012-07-25,2012.0,2012-05-17,2012-05-17,118000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-69.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49336,/organization/zova,Zova,Sports,0,operating,AUS,Brisbane,1.0,2013-09-01,2013.0,2013-08-01,2013-08-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-31.0
49343,/organization/zqgame,ZQGame,Games,4220018,operating,USA,El Segundo,1.0,2011-03-01,2011.0,2007-12-01,2007-12-01,0.0,4220018.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4220018.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1186.0
49365,/organization/zulily,zulily,E-Commerce,138600000,operating,USA,Seattle,4.0,2010-01-01,2010.0,2009-12-17,2012-11-15,0.0,138600000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4600000.0,6000000.0,43000000.0,85000000.0,0.0,0.0,0.0,0.0,-15.0
49426,/organization/zynga,Zynga,Technology,866550786,operating,USA,San Francisco,9.0,2007-07-01,2007.0,2007-01-01,2011-02-18,0.0,866550786.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15026000.0,355187000.0,490000000.0,0.0,0.0,0.0,0.0,0.0,-181.0
49435,/organization/zzzzapp-com,Zzzzapp Wireless ltd.,Web Development,97398,operating,HRV,Split,5.0,2012-05-13,2012.0,2011-11-01,2014-09-10,71525.0,0.0,0.0,25873.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-194.0

### Let's exclude those rows from the dataset

In [68]:
startups = startups.loc[startups.delta_founded_vs_firstfunding >= 0]

In [70]:
startups.shape

(30491, 33)

### Cleaning and exploration has been completed, so let's save a version of the csv and move towards the enrichment of the dataset

In [71]:
startups.to_csv('Cleaned_startups.csv')