### Let's train another model but this time let's use the log(10) of the valuation as the predictor. That way it will estimate the number of digits in the valuation instead of the absolute valuation, which is more appropriate

In [2]:
import pandas as pd

In [3]:
pd.set_option("display.max_columns", None)
startups = pd.read_csv("../../notebooks/Web_scraping/datasets/startups_with_valuation_temp.csv")

In [4]:
startups.head()

,Unnamed: 0,permalink,name,market,funding_total_usd,status,country_code,city,funding_rounds,founded_at,founded_year,first_funding_at,last_funding_at,seed,venture,equity_crowdfunding,convertible_note,debt_financing,angel,grant,private_equity,post_ipo_equity,post_ipo_debt,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H,delta_founded_vs_firstfunding,valuation
0,0,/organization/waywire,#waywire,News,1750000,acquired,USA,New York,1.0,2012-06-01,2012.0,2012-06-30,2012-06-30,1750000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,29.0,NaN
1,3,/organization/in-touch-network,(In)Touch Network,Electronics,1500000,operating,GBR,London,1.0,2011-04-01,2011.0,2011-04-01,2011-04-01,1500000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
2,4,/organization/r-ranch-and-mine,-R- Ranch and Mine,Tourism,60000,operating,USA,Fort Worth,2.0,2014-01-01,2014.0,2014-08-17,2014-09-26,0.0,0.0,60000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,228.0,NaN
3,8,/organization/004-technologies,004 Technologies,Software,0,operating,USA,Champaign,1.0,2010-01-01,2010.0,2014-07-24,2014-07-24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1665.0,NaN
4,10,/organization/1-2-3-listo,"1,2,3 Listo",E-Commerce,40000,operating,CHL,Las Condes,1.0,2012-01-01,2012.0,2013-02-18,2013-02-18,40000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,414.0,NaN

In [5]:
startups.shape

(30491, 35)

In [6]:
startups = startups[startups["valuation"].notnull()]

In [7]:
startups.shape

(19809, 35)

In [8]:
def valuation_cleaner(x):
    if "—" in x:
        a = x.split("—")
        return a[1]
    else:
        return x

In [9]:
valuation_cleaner("€4.4b")

'€4.4b'

In [10]:
startups["valuation"] = startups["valuation"].apply(valuation_cleaner)

In [11]:
startups.head()

,Unnamed: 0,permalink,name,market,funding_total_usd,status,country_code,city,funding_rounds,founded_at,founded_year,first_funding_at,last_funding_at,seed,venture,equity_crowdfunding,convertible_note,debt_financing,angel,grant,private_equity,post_ipo_equity,post_ipo_debt,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H,delta_founded_vs_firstfunding,valuation
8,15,/organization/10-minutes-with,10 Minutes With,Education,4400000,operating,GBR,London,2.0,2013-01-01,2013.0,2013-01-01,2014-10-09,400000.0,4000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22m
10,17,/organization/1000-corks,1000 Corks,Search,40000,operating,USA,Lake Oswego,1.0,2008-01-01,2008.0,2011-08-23,2011-08-23,40000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1330.0,218k
15,27,/organization/100plus,100Plus,Analytics,1250000,acquired,USA,San Francisco,2.0,2011-09-16,2011.0,2011-11-02,2011-11-30,750000.0,500000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.0,136m
16,28,/organization/1010data,1010data,Software,35000000,operating,USA,New York,1.0,2000-01-01,2000.0,2010-03-08,2010-03-08,0.0,35000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3719.0,210m
18,30,/organization/10bestthings,10BestThings,Curated Web,50000,closed,USA,Cleveland,1.0,2009-04-01,2009.0,2009-04-01,2009-04-01,50000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,273k

### Given that we want all the values to be consistent let's show all valuations absolute units

In [12]:
def integer_converter(x):
    if "k" in x:
        valuation = x.replace("k","")
        valuation_clean = valuation.replace("€","")
        return round(float(valuation_clean)*1000)
    elif "m" in x:
        valuation = x.replace("m","")
        valuation_clean = valuation.replace("€","")
        return round(float(valuation_clean)*1000000)
    elif "b" in x:
        valuation = x.replace("b","")
        valuation_clean = valuation.replace("€","")
        return round(float(valuation_clean)*1000000000)

In [13]:
startups["valuation"] = startups["valuation"].apply(integer_converter)

In [14]:
startups.head()

,Unnamed: 0,permalink,name,market,funding_total_usd,status,country_code,city,funding_rounds,founded_at,founded_year,first_funding_at,last_funding_at,seed,venture,equity_crowdfunding,convertible_note,debt_financing,angel,grant,private_equity,post_ipo_equity,post_ipo_debt,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H,delta_founded_vs_firstfunding,valuation
8,15,/organization/10-minutes-with,10 Minutes With,Education,4400000,operating,GBR,London,2.0,2013-01-01,2013.0,2013-01-01,2014-10-09,400000.0,4000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22000000.0
10,17,/organization/1000-corks,1000 Corks,Search,40000,operating,USA,Lake Oswego,1.0,2008-01-01,2008.0,2011-08-23,2011-08-23,40000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1330.0,218000.0
15,27,/organization/100plus,100Plus,Analytics,1250000,acquired,USA,San Francisco,2.0,2011-09-16,2011.0,2011-11-02,2011-11-30,750000.0,500000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.0,136000000.0
16,28,/organization/1010data,1010data,Software,35000000,operating,USA,New York,1.0,2000-01-01,2000.0,2010-03-08,2010-03-08,0.0,35000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3719.0,210000000.0
18,30,/organization/10bestthings,10BestThings,Curated Web,50000,closed,USA,Cleveland,1.0,2009-04-01,2009.0,2009-04-01,2009-04-01,50000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,273000.0

### I have now converted the valuation to absolute units instead of millions, and will now create a new column with the log of it

In [15]:
startups.drop('Unnamed: 0', axis=1, inplace=True)

In [17]:
import numpy as np

In [20]:
startups["log_valuation"] = round(np.log10(startups["valuation"]), 0)

In [21]:
startups.head()

,permalink,name,market,funding_total_usd,status,country_code,city,funding_rounds,founded_at,founded_year,first_funding_at,last_funding_at,seed,venture,equity_crowdfunding,convertible_note,debt_financing,angel,grant,private_equity,post_ipo_equity,post_ipo_debt,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H,delta_founded_vs_firstfunding,valuation,log_valuation
8,/organization/10-minutes-with,10 Minutes With,Education,4400000,operating,GBR,London,2.0,2013-01-01,2013.0,2013-01-01,2014-10-09,400000.0,4000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22000000.0,7.0
10,/organization/1000-corks,1000 Corks,Search,40000,operating,USA,Lake Oswego,1.0,2008-01-01,2008.0,2011-08-23,2011-08-23,40000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1330.0,218000.0,5.0
15,/organization/100plus,100Plus,Analytics,1250000,acquired,USA,San Francisco,2.0,2011-09-16,2011.0,2011-11-02,2011-11-30,750000.0,500000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.0,136000000.0,8.0
16,/organization/1010data,1010data,Software,35000000,operating,USA,New York,1.0,2000-01-01,2000.0,2010-03-08,2010-03-08,0.0,35000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3719.0,210000000.0,8.0
18,/organization/10bestthings,10BestThings,Curated Web,50000,closed,USA,Cleveland,1.0,2009-04-01,2009.0,2009-04-01,2009-04-01,50000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,273000.0,5.0

### Now let's drop the valuation column and use as predictor the log

In [22]:
startups.drop('valuation', axis=1, inplace=True)

### There are some categorical values that I would like to take into account, such as the country or market, for that we will use rank encoding initially

In [23]:
top_20_countries = startups.country_code.value_counts().head(20)

In [24]:
top_20_countries_df = pd.DataFrame(top_20_countries)

In [25]:
top_20_countries_df["rank"] = range(1, len(top_20_countries_df)+1)

In [26]:
top_20_countries_df.drop('country_code', axis=1, inplace=True)

In [27]:
countries = top_20_countries_df.to_dict(orient="index")

In [28]:
countries["USA"]['rank']

1

In [29]:
top_20_countries_list = countries.keys()

In [30]:
def country_ranking(x):
    if x in top_20_countries_list:
        return countries[x]['rank']
    else:
        return 21

In [31]:
ranking_country = []

In [32]:
for i, row in startups.iterrows():
    name = row["country_code"]
    ranking = country_ranking(name)
    ranking_country.append(ranking)

In [33]:
ranking_country[:20]

[2, 1, 1, 1, 1, 12, 1, 12, 1, 21, 15, 1, 11, 1, 1, 1, 8, 1, 1, 1]

In [34]:
startups["country_ranking"] = ranking_country

In [35]:
startups.head()

,permalink,name,market,funding_total_usd,status,country_code,city,funding_rounds,founded_at,founded_year,first_funding_at,last_funding_at,seed,venture,equity_crowdfunding,convertible_note,debt_financing,angel,grant,private_equity,post_ipo_equity,post_ipo_debt,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H,delta_founded_vs_firstfunding,log_valuation,country_ranking
8,/organization/10-minutes-with,10 Minutes With,Education,4400000,operating,GBR,London,2.0,2013-01-01,2013.0,2013-01-01,2014-10-09,400000.0,4000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,2
10,/organization/1000-corks,1000 Corks,Search,40000,operating,USA,Lake Oswego,1.0,2008-01-01,2008.0,2011-08-23,2011-08-23,40000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1330.0,5.0,1
15,/organization/100plus,100Plus,Analytics,1250000,acquired,USA,San Francisco,2.0,2011-09-16,2011.0,2011-11-02,2011-11-30,750000.0,500000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.0,8.0,1
16,/organization/1010data,1010data,Software,35000000,operating,USA,New York,1.0,2000-01-01,2000.0,2010-03-08,2010-03-08,0.0,35000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3719.0,8.0,1
18,/organization/10bestthings,10BestThings,Curated Web,50000,closed,USA,Cleveland,1.0,2009-04-01,2009.0,2009-04-01,2009-04-01,50000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,1

### I have elaborated a rank encoding column for the country of each startup based on the frequency of the country within the dataset. Now I will perform the same operation but for the market

In [36]:
top_20_markets = startups.market.value_counts().head(20)

In [37]:
top_20_markets

 Software                2247
 Biotechnology           1683
 Mobile                   913
 Enterprise Software      674
 E-Commerce               673
 Curated Web              649
 Health Care              610
 Hardware + Software      539
 Advertising              488
 Games                    468
 Clean Technology         466
 Health and Wellness      375
 Social Media             364
 Education                333
 Analytics                330
 Finance                  318
 Semiconductors           270
 Security                 267
 Manufacturing            237
 Web Hosting              211
Name: market, dtype: int64

In [38]:
top_20_markets_df = pd.DataFrame(top_20_markets)

In [39]:
top_20_markets_df["rank"] = range(1, len(top_20_markets_df)+1)

In [40]:
top_20_markets_df.drop('market', axis=1, inplace=True)

In [41]:
markets = top_20_markets_df.to_dict(orient="index")

In [42]:
markets[" Finance "]["rank"]

16

In [43]:
top_20_markets_list = markets.keys()

In [44]:
def market_ranking(x):
    if x in top_20_markets_list:
        return markets[x]['rank']
    else:
        return 21

In [45]:
ranking_market = []

In [46]:
for i, row in startups.iterrows():
    name = row["market"]
    ranking = market_ranking(name)
    ranking_market.append(ranking)

In [47]:
ranking_market[:20]

[14, 21, 15, 1, 6, 21, 2, 3, 21, 21, 1, 19, 3, 21, 1, 1, 16, 5, 21, 1]

In [48]:
startups["market_ranking"] = ranking_market

In [49]:
startups.head()

,permalink,name,market,funding_total_usd,status,country_code,city,funding_rounds,founded_at,founded_year,first_funding_at,last_funding_at,seed,venture,equity_crowdfunding,convertible_note,debt_financing,angel,grant,private_equity,post_ipo_equity,post_ipo_debt,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H,delta_founded_vs_firstfunding,log_valuation,country_ranking,market_ranking
8,/organization/10-minutes-with,10 Minutes With,Education,4400000,operating,GBR,London,2.0,2013-01-01,2013.0,2013-01-01,2014-10-09,400000.0,4000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,2,14
10,/organization/1000-corks,1000 Corks,Search,40000,operating,USA,Lake Oswego,1.0,2008-01-01,2008.0,2011-08-23,2011-08-23,40000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1330.0,5.0,1,21
15,/organization/100plus,100Plus,Analytics,1250000,acquired,USA,San Francisco,2.0,2011-09-16,2011.0,2011-11-02,2011-11-30,750000.0,500000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.0,8.0,1,15
16,/organization/1010data,1010data,Software,35000000,operating,USA,New York,1.0,2000-01-01,2000.0,2010-03-08,2010-03-08,0.0,35000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3719.0,8.0,1,1
18,/organization/10bestthings,10BestThings,Curated Web,50000,closed,USA,Cleveland,1.0,2009-04-01,2009.0,2009-04-01,2009-04-01,50000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,1,6

### Let's now drop those columns that we will not be using

In [51]:
startups.drop(['permalink', 'name', 'market','status', 'country_code', 'city', 'founded_at', 'first_funding_at', 'last_funding_at'], axis=1, inplace=True)

In [52]:
X = startups.drop('log_valuation', axis=1)

In [53]:
y = startups['log_valuation']

In [54]:
from sklearn.model_selection import train_test_split as tts

In [55]:
X_train, X_test, y_train, y_test = tts(X, y, test_size=0.2)

### Let's train a Simple Linear Regression

In [56]:
from sklearn.linear_model import LinearRegression as LinReg

In [57]:
linreg=LinReg()

In [58]:
linreg.fit(X_train, y_train)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [60]:
np.any(np.isnan(startups))

True

In [61]:
np.all(np.isfinite(startups))

False

In [62]:
startups.isnull().any()

funding_total_usd                False
funding_rounds                   False
founded_year                     False
seed                             False
venture                          False
equity_crowdfunding              False
convertible_note                 False
debt_financing                   False
angel                            False
grant                            False
private_equity                   False
post_ipo_equity                  False
post_ipo_debt                    False
secondary_market                 False
product_crowdfunding             False
round_A                          False
round_B                          False
round_C                          False
round_D                          False
round_E                          False
round_F                          False
round_G                          False
round_H                          False
delta_founded_vs_firstfunding    False
log_valuation                     True
country_ranking                  False
market_ranking                   False
dtype: bool

In [65]:
startups= startups[startups["log_valuation"].notnull()]

In [70]:
X = startups.drop('log_valuation', axis=1)

In [71]:
y = startups['log_valuation']

In [72]:
X_train, X_test, y_train, y_test = tts(X, y, test_size=0.2)

In [73]:
linreg.fit(X_train, y_train)

LinearRegression()

In [74]:
linreg.coef_

array([ 1.90451830e-08,  5.99821089e-02, -3.56065654e-02,  1.00976130e-07,
        3.58823950e-10,  2.74681301e-08,  1.77964449e-08, -1.80874899e-08,
        3.47894829e-08, -1.74960211e-08, -1.59982020e-08, -1.86126985e-08,
       -1.78099530e-08, -1.71087633e-08, -6.70418420e-08,  1.32874465e-08,
       -5.44365840e-09, -9.53970883e-09, -1.64569156e-08, -1.50630203e-08,
       -1.78211438e-08, -1.51951772e-08, -2.46559423e-08,  3.85850127e-06,
       -1.23982852e-02, -3.88868056e-03])

In [75]:
linreg.intercept_

78.28101668707065

In [76]:
y_pred=linreg.predict(X_test)

In [77]:
y_pred[:10]

array([7.04947971, 7.65031634, 6.85740677, 6.6503433 , 6.66808121,
       6.60876654, 6.44329324, 6.68070853, 7.03470238, 6.46366019])

In [78]:
y_test[:10]

7838     6.0
19297    7.0
18722    7.0
17006    6.0
5210     7.0
23508    7.0
14239    6.0
11371    5.0
7840     6.0
19175    7.0
Name: log_valuation, dtype: float64

### Let's take a look at the metrics

In [79]:
from sklearn import metrics
import numpy as np

In [80]:
'MAE - Error Medio Absoluto', metrics.mean_absolute_error(y_test, y_pred)

('MAE - Error Medio Absoluto', 0.7253143234437757)

In [81]:
'MSE - Error Cuadratico Medio', metrics.mean_squared_error(y_test, y_pred)

('MSE - Error Cuadratico Medio', 0.8985385371075909)

In [82]:
'RMSE - Raiz Error Cuadratico Medio', metrics.mean_squared_error(y_test, y_pred)**0.5

('RMSE - Raiz Error Cuadratico Medio', 0.9479127265247529)

In [83]:
'R2 - Coeficiente de Determinacion', metrics.r2_score(y_test, y_pred)

('R2 - Coeficiente de Determinacion', 0.23049620243843139)

### This model looks  a bit more promising

### Let's test with some others: Ridge, Lasso, SGDRegressor, KNeighbors, GradientBoosting

In [84]:
from sklearn.linear_model import Ridge, Lasso

from sklearn.linear_model import SGDRegressor

from sklearn.neighbors import KNeighborsRegressor

from sklearn.ensemble import GradientBoostingRegressor

In [85]:
models={
    'ridge': Ridge(),
    'lasso': Lasso(),
    'sgd': SGDRegressor(),
    'knn': KNeighborsRegressor(),
    'grad': GradientBoostingRegressor()
}

In [87]:
for name, model in models.items():  # entrenamiento en bucle
    print('Training: ', name)
    model.fit(X_train, y_train)

Training:  ridge
Training:  lasso

/home/alvarogb/anaconda3/envs/ironhack/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:147: LinAlgWarning: Ill-conditioned matrix (rcond=1.03292e-16): result may not be accurate.
  return linalg.solve(A, Xy, sym_pos=True,
/home/alvarogb/anaconda3/envs/ironhack/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:530: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 7014.36209589731, tolerance: 1.8686201969199312
  model = cd_fast.enet_coordinate_descent(

Training:  sgd
Training:  knn
Training:  grad

In [88]:
for name, model in models.items():
    
    print('Modelo : ', name)
    
    y_pred=model.predict(X_test)
    
    y_pred_train=model.predict(X_train)
    
    print('RMSE - Raiz Error Cuadratico Medio', metrics.mean_squared_error(y_test, y_pred)**0.5)
    print('R2 - Coeficiente de Determinacion', metrics.r2_score(y_test, y_pred))
    
    print('RMSE_train - Raiz Error Cuadratico Medio', metrics.mean_squared_error(y_train, y_pred_train)**0.5)
    print('R2_train - Coeficiente de Determinacion', metrics.r2_score(y_train, y_pred_train))
    
    print()

Modelo :  ridge
RMSE - Raiz Error Cuadratico Medio 0.947912863680203
R2 - Coeficiente de Determinacion 0.23049597975622782
RMSE_train - Raiz Error Cuadratico Medio 0.9253582812947981
R2_train - Coeficiente de Determinacion 0.273954852755551

Modelo :  lasso
RMSE - Raiz Error Cuadratico Medio 0.9678854038241617
R2 - Coeficiente de Determinacion 0.19772743625720712
RMSE_train - Raiz Error Cuadratico Medio 0.9409038982213949
R2_train - Coeficiente de Determinacion 0.24935545856754704

Modelo :  sgd
RMSE - Raiz Error Cuadratico Medio 9.157527699602995e+24
R2 - Coeficiente de Determinacion -7.181754269969564e+49
RMSE_train - Raiz Error Cuadratico Medio 4.446707747134759e+25
R2_train - Coeficiente de Determinacion -1.676567214698018e+51

Modelo :  knn
RMSE - Raiz Error Cuadratico Medio 0.7001117672364304
R2 - Coeficiente de Determinacion 0.5802324972394498
RMSE_train - Raiz Error Cuadratico Medio 0.5657345150597731
R2_train - Coeficiente de Determinacion 0.7286254313017478

Modelo :  grad
RMSE - Raiz Error Cuadratico Medio 0.6432684998253341
R2 - Coeficiente de Determinacion 0.6456286286160574
RMSE_train - Raiz Error Cuadratico Medio 0.6143286022601471
R2_train - Coeficiente de Determinacion 0.6800034714271033

### Let's perform cross validation to increase visibility for the models

In [89]:
from sklearn.model_selection import cross_val_score as cvs

### CV iterating by models

In [90]:
for name, model in models.items():
    scores=cvs(model, X, y, scoring='r2', cv=5)
    print('Modelo: ', name, 'Score: ', np.mean(scores))

/home/alvarogb/anaconda3/envs/ironhack/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:147: LinAlgWarning: Ill-conditioned matrix (rcond=5.48915e-21): result may not be accurate.
  return linalg.solve(A, Xy, sym_pos=True,
/home/alvarogb/anaconda3/envs/ironhack/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:147: LinAlgWarning: Ill-conditioned matrix (rcond=9.23839e-17): result may not be accurate.
  return linalg.solve(A, Xy, sym_pos=True,
/home/alvarogb/anaconda3/envs/ironhack/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:147: LinAlgWarning: Ill-conditioned matrix (rcond=9.35919e-17): result may not be accurate.
  return linalg.solve(A, Xy, sym_pos=True,
/home/alvarogb/anaconda3/envs/ironhack/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:147: LinAlgWarning: Ill-conditioned matrix (rcond=1.06639e-16): result may not be accurate.
  return linalg.solve(A, Xy, sym_pos=True,

Modelo:  ridge Score:  0.1936202990422214

/home/alvarogb/anaconda3/envs/ironhack/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:530: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 7048.13186688549, tolerance: 1.8895870739712202
  model = cd_fast.enet_coordinate_descent(
/home/alvarogb/anaconda3/envs/ironhack/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:530: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 6963.515388947619, tolerance: 1.8564829914799699
  model = cd_fast.enet_coordinate_descent(
/home/alvarogb/anaconda3/envs/ironhack/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:530: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 7139.943672653577, tolerance: 1.8891546229094447
  model = cd_fast.enet_coordinate_descent(
/home/alvarogb/anaconda3/envs/ironhack/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:530: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 7053.791828371705, tolerance: 1.8498274913221795
  model = cd_fast.enet_coordinate_descent(
/home/alvarogb/anaconda3/envs/ironhack/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:530: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 7001.096780477975, tolerance: 1.8395846260649975
  model = cd_fast.enet_coordinate_descent(

Modelo:  lasso Score:  0.15175111953853498
Modelo:  sgd Score:  -1.7982833231572154e+50
Modelo:  knn Score:  0.5860078097405247
Modelo:  grad Score:  0.6546347749968128

### It looks as though the grad model has the best score