### Let's train another  model with the variables we have so far

In [1]:
import pandas as pd

In [2]:
pd.set_option("display.max_columns", None)
startups = pd.read_csv("../../dataset/Cleaned_startups.csv")

In [3]:
startups.head()

,Unnamed: 0,permalink,name,market,funding_total_usd,status,country_code,city,funding_rounds,founded_at,founded_year,first_funding_at,last_funding_at,seed,venture,equity_crowdfunding,convertible_note,debt_financing,angel,grant,private_equity,post_ipo_equity,post_ipo_debt,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H,delta_founded_vs_firstfunding
0,0,/organization/waywire,#waywire,News,1750000,acquired,USA,New York,1.0,2012-06-01,2012.0,2012-06-30,2012-06-30,1750000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,29.0
1,3,/organization/in-touch-network,(In)Touch Network,Electronics,1500000,operating,GBR,London,1.0,2011-04-01,2011.0,2011-04-01,2011-04-01,1500000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,4,/organization/r-ranch-and-mine,-R- Ranch and Mine,Tourism,60000,operating,USA,Fort Worth,2.0,2014-01-01,2014.0,2014-08-17,2014-09-26,0.0,0.0,60000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,228.0
3,8,/organization/004-technologies,004 Technologies,Software,0,operating,USA,Champaign,1.0,2010-01-01,2010.0,2014-07-24,2014-07-24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1665.0
4,10,/organization/1-2-3-listo,"1,2,3 Listo",E-Commerce,40000,operating,CHL,Las Condes,1.0,2012-01-01,2012.0,2013-02-18,2013-02-18,40000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,414.0

In [4]:
startups.drop('Unnamed: 0', axis=1, inplace=True)

In [5]:
startups.sample(5)

,permalink,name,market,funding_total_usd,status,country_code,city,funding_rounds,founded_at,founded_year,first_funding_at,last_funding_at,seed,venture,equity_crowdfunding,convertible_note,debt_financing,angel,grant,private_equity,post_ipo_equity,post_ipo_debt,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H,delta_founded_vs_firstfunding
8389,/organization/empowrnet,EmpowrNet,Software,40000,operating,USA,Tulsa,1.0,2010-01-01,2010.0,2013-01-01,2013-01-01,40000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1096.0
15557,/organization/makemytrip-com,MakeMyTrip.com,Transportation,28000000,operating,IND,Gurgaon,2.0,2000-01-01,2000.0,2006-12-14,2007-10-08,0.0,28000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13000000.0,15000000.0,0.0,0.0,0.0,0.0,0.0,2539.0
4062,/organization/broadcastr,Broadcastr,Parenting,2574556,closed,USA,Brooklyn,1.0,2010-01-01,2010.0,2012-12-10,2012-12-10,0.0,2574556.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1074.0
27456,/organization/tuck-company,Tuck & Company,Enterprise Software,2904978,operating,KOR,Seoul,1.0,2011-04-11,2011.0,2014-05-01,2014-05-01,0.0,2904978.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1116.0
30253,/organization/zerovm,ZeroVM,IaaS,1538000,acquired,USA,San Antonio,2.0,2011-05-01,2011.0,2013-01-14,2013-04-30,1538000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,624.0

### My predictor is going to be a multiclass column "status", and the variables are going to be all the numerical ones

In [6]:
startups.dtypes

permalink                         object
name                              object
market                            object
funding_total_usd                  int64
status                            object
country_code                      object
city                              object
funding_rounds                   float64
founded_at                        object
founded_year                     float64
first_funding_at                  object
last_funding_at                   object
seed                             float64
venture                          float64
equity_crowdfunding              float64
convertible_note                 float64
debt_financing                   float64
angel                            float64
grant                            float64
private_equity                   float64
post_ipo_equity                  float64
post_ipo_debt                    float64
secondary_market                 float64
product_crowdfunding             float64
round_A                          float64
round_B                          float64
round_C                          float64
round_D                          float64
round_E                          float64
round_F                          float64
round_G                          float64
round_H                          float64
delta_founded_vs_firstfunding    float64
dtype: object

### There are some categorical values that I would like to take into account, such as the country or market, for that we will use rank encoding initially

In [13]:
top_20_countries = startups.country_code.value_counts().head(20)

In [18]:
top_20_countries_df = pd.DataFrame(top_20_countries)

In [26]:
top_20_countries_df["rank"] = range(1, len(top_20_countries_df)+1)

In [28]:
top_20_countries_df.drop('country_code', axis=1, inplace=True)

In [50]:
countries = top_20_countries_df.to_dict(orient="index")

In [51]:
countries["USA"]['rank']

1

In [52]:
top_20_countries_list = countries.keys()

In [55]:
def country_ranking(x):
    if x in top_20_countries_list:
        return countries[x]['rank']
    else:
        return 21

In [59]:
ranking_country = []

In [60]:
for i, row in startups.iterrows():
    name = row["country_code"]
    ranking = country_ranking(name)
    ranking_country.append(ranking)

In [62]:
ranking_country[:20]

[1, 2, 1, 1, 21, 1, 1, 1, 2, 1, 1, 1, 6, 7, 1, 1, 1, 3, 1, 13]

In [63]:
startups["country_ranking"] = ranking_country

In [64]:
startups.head()

,permalink,name,market,funding_total_usd,status,country_code,city,funding_rounds,founded_at,founded_year,first_funding_at,last_funding_at,seed,venture,equity_crowdfunding,convertible_note,debt_financing,angel,grant,private_equity,post_ipo_equity,post_ipo_debt,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H,delta_founded_vs_firstfunding,country_ranking
0,/organization/waywire,#waywire,News,1750000,acquired,USA,New York,1.0,2012-06-01,2012.0,2012-06-30,2012-06-30,1750000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,29.0,1
1,/organization/in-touch-network,(In)Touch Network,Electronics,1500000,operating,GBR,London,1.0,2011-04-01,2011.0,2011-04-01,2011-04-01,1500000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
2,/organization/r-ranch-and-mine,-R- Ranch and Mine,Tourism,60000,operating,USA,Fort Worth,2.0,2014-01-01,2014.0,2014-08-17,2014-09-26,0.0,0.0,60000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,228.0,1
3,/organization/004-technologies,004 Technologies,Software,0,operating,USA,Champaign,1.0,2010-01-01,2010.0,2014-07-24,2014-07-24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1665.0,1
4,/organization/1-2-3-listo,"1,2,3 Listo",E-Commerce,40000,operating,CHL,Las Condes,1.0,2012-01-01,2012.0,2013-02-18,2013-02-18,40000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,414.0,21

### I have elaborated a rank encoding column for the country of each startup based on the frequency of the country within the dataset. Now I will perform the same operation but for the market

In [65]:
top_20_markets = startups.market.value_counts().head(20)

In [66]:
top_20_markets

 Software                3358
 Biotechnology           2311
 Mobile                  1314
 E-Commerce              1140
 Curated Web             1025
 Enterprise Software      938
 Health Care              790
 Hardware + Software      742
 Advertising              734
 Games                    730
 Clean Technology         679
 Health and Wellness      599
 Finance                  554
 Education                545
 Social Media             530
 Analytics                453
 Manufacturing            444
 Security                 364
 Semiconductors           345
 Consulting               343
Name: market, dtype: int64

In [67]:
top_20_markets_df = pd.DataFrame(top_20_markets)

In [68]:
top_20_markets_df["rank"] = range(1, len(top_20_markets_df)+1)

In [71]:
top_20_markets_df.drop('market', axis=1, inplace=True)

In [72]:
markets = top_20_markets_df.to_dict(orient="index")

In [76]:
markets[" Finance "]["rank"]

13

In [77]:
top_20_markets_list = markets.keys()

In [79]:
def market_ranking(x):
    if x in top_20_markets_list:
        return markets[x]['rank']
    else:
        return 21

In [80]:
ranking_market = []

In [81]:
for i, row in startups.iterrows():
    name = row["market"]
    ranking = market_ranking(name)
    ranking_market.append(ranking)

In [83]:
ranking_market[:20]

[21, 21, 21, 1, 4, 12, 12, 21, 14, 4, 21, 5, 21, 21, 21, 16, 1, 21, 5, 21]

In [84]:
startups["market_ranking"] = ranking_market

In [85]:
startups.head()

,permalink,name,market,funding_total_usd,status,country_code,city,funding_rounds,founded_at,founded_year,first_funding_at,last_funding_at,seed,venture,equity_crowdfunding,convertible_note,debt_financing,angel,grant,private_equity,post_ipo_equity,post_ipo_debt,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H,delta_founded_vs_firstfunding,country_ranking,market_ranking
0,/organization/waywire,#waywire,News,1750000,acquired,USA,New York,1.0,2012-06-01,2012.0,2012-06-30,2012-06-30,1750000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,29.0,1,21
1,/organization/in-touch-network,(In)Touch Network,Electronics,1500000,operating,GBR,London,1.0,2011-04-01,2011.0,2011-04-01,2011-04-01,1500000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,21
2,/organization/r-ranch-and-mine,-R- Ranch and Mine,Tourism,60000,operating,USA,Fort Worth,2.0,2014-01-01,2014.0,2014-08-17,2014-09-26,0.0,0.0,60000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,228.0,1,21
3,/organization/004-technologies,004 Technologies,Software,0,operating,USA,Champaign,1.0,2010-01-01,2010.0,2014-07-24,2014-07-24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1665.0,1,1
4,/organization/1-2-3-listo,"1,2,3 Listo",E-Commerce,40000,operating,CHL,Las Condes,1.0,2012-01-01,2012.0,2013-02-18,2013-02-18,40000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,414.0,21,4

### Let's now drop those columns that we will not be using

In [86]:
startups.drop(['permalink', 'name', 'market', 'country_code', 'city', 'founded_at', 'first_funding_at', 'last_funding_at'], axis=1, inplace=True)

In [87]:
X = startups.drop('status', axis=1)

In [88]:
y = startups['status']

In [89]:
from sklearn.model_selection import train_test_split as tts

In [90]:
X_train, X_test, y_train, y_test = tts(X, y, test_size=0.2)

In [91]:
from sklearn.linear_model import LogisticRegression

In [92]:
log_1 = LogisticRegression()

In [93]:
log_1.fit(X_train, y_train)

/home/alvarogb/anaconda3/envs/ironhack/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [94]:
y_pred_test = log_1.predict(X_test)

In [95]:
y_pred_train = log_1.predict(X_train)

### Let's take a look at some metrics now

In [96]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, fbeta_score

In [97]:
accuracy_test = accuracy_score(y_true = y_test, y_pred=y_pred_test)

In [98]:
accuracy_train = accuracy_score(y_true = y_train, y_pred=y_pred_train)

In [99]:
accuracy_test.round(3)

0.87

In [100]:
accuracy_train.round(3)

0.864